#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep  2 12:28:33 2017

@author: tizianomartinhernando
"""

nombres=['juan','ana','marcos','carlos', 'luis']
cantidad=0
x=0
while x<len(nombres):
    if len(nombres[x])>=5:
        cantidad=cantidad+1
    x=x+1
print('Todos los nombres son: ')
print(nombres)
print('Cantidad de nombres con 5 o mas caracteres: ')
print(cantidad)


'''
Definir una lista que almacene por asignación los nombres de 5 personas. Contar cuantos de esos nombres tienen 5 o más caracteres.

'''
